In [1]:
import torch

[01-basics](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/01-basics/pytorch_basics/main.py)

#### 1. Basic autograd example 1

In [11]:
x = torch.tensor(1., requires_grad=True)

In [4]:
w = torch.tensor(2., requires_grad=True)

In [5]:
b = torch.tensor(3., requires_grad=True)

In [6]:
y = w * x + b

In [7]:
y.backward()

In [8]:
x.grad

tensor(2.)

In [9]:
w.grad

tensor(1.)

In [10]:
b.grad

tensor(1.)

#### 2. Basic autograd example 2

In [13]:
x = torch.randn(10, 3)

In [14]:
y = torch.randn(10, 2)

In [15]:
x

tensor([[ 0.9021,  1.3369, -0.4770],
        [ 0.9566,  1.0079,  1.4529],
        [ 1.2982, -1.5932,  0.5055],
        [-0.4999, -0.5420,  0.0185],
        [ 0.1192, -1.5340,  0.3998],
        [ 0.2860, -2.8127, -1.3763],
        [ 0.0413,  1.2375, -0.3573],
        [ 0.5178, -0.9177, -1.2993],
        [-0.3498,  0.2697, -1.3623],
        [-0.1420,  0.4822,  1.0782]])

In [16]:
import torch.nn as nn

In [17]:
linear = nn.Linear(3, 2)

In [18]:
linear.weight

Parameter containing:
tensor([[ 0.1291,  0.3313,  0.1718],
        [-0.5253,  0.2451,  0.3261]], requires_grad=True)

In [19]:
linear.bias

Parameter containing:
tensor([-0.4562, -0.1953], requires_grad=True)

In [20]:
criterion = nn.MSELoss()

In [21]:
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [22]:
linear.parameters()

<generator object Module.parameters at 0x7fccfc7a15c8>

In [23]:
pred = linear(x)

In [24]:
pred

tensor([[ 0.0212, -0.4971],
        [ 0.2508,  0.0231],
        [-0.7296, -1.1028],
        [-0.6971, -0.0595],
        [-0.8803, -0.5035],
        [-1.5876, -1.4837],
        [-0.1023, -0.0302],
        [-0.9167, -1.1159],
        [-0.6461, -0.3897],
        [-0.1295,  0.3491]], grad_fn=<AddmmBackward>)

In [25]:
loss = criterion(pred, y)

In [26]:
loss

tensor(1.3093, grad_fn=<MseLossBackward>)

In [27]:
loss.backward()

In [28]:
linear.weight.grad

tensor([[-0.2643,  1.2056,  0.5200],
        [-0.1433,  0.4817,  0.7865]])

In [29]:
linear.bias.grad

tensor([-0.3878, -0.2507])

In [30]:
optimizer.step()

In [31]:
linear.weight

Parameter containing:
tensor([[ 0.1317,  0.3193,  0.1666],
        [-0.5239,  0.2403,  0.3183]], requires_grad=True)

In [32]:
pred = linear(x)

In [34]:
loss = criterion(pred, y)

In [35]:
loss

tensor(1.2808, grad_fn=<MseLossBackward>)

#### 3. Loading data from numpy

In [36]:
import numpy as np

In [37]:
x = np.array([[1,2], [3,4]])

In [38]:
y = torch.from_numpy(x)

In [39]:
z = y.numpy()

In [40]:
x, y, z

(array([[1, 2],
        [3, 4]]),
 tensor([[1, 2],
         [3, 4]]),
 array([[1, 2],
        [3, 4]]))